version: "3.1"
 
services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint_man
      POSTGRES_PASSWORD: Dogs0-Cats1-birds3!
      POSTGRES_DB: peppermint
 
  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$BASE_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "peppermint_man"
      DB_PASSWORD: "Dogs0-Cats1-birds3!"
      DB_HOST: "peppermint_postgres"
      SECRET: 'notEvenSure123'
      API_URL: "http://peppermint.goobyfrs.net:5003"
 
volumes:
 pgdata: